name: Build and Publish Extension

on:
  push:
    branches: [main]

jobs:
  build-and-publish:
    strategy:
      matrix:
        platform: [
          {os: windows-latest, vscode: win32-x64},
          {os: ubuntu-latest, vscode: linux-x64},
          {os: macos-latest, vscode: darwin-arm64},
        ]

    runs-on: ${{ matrix.platform.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "20"

    - name: Install dependencies
      run: npm install

    - name: Package extension
      run: npx vsce publish --target ${{ matrix.platform.vscode }} -p ${{ secrets.VSCODE_MARKETPLACE_TOKEN }}

